### ISSUE TITLE
Normalize method inside SeoPage.php bug

### ISSUE THREAD

**Issue by slash890** [sonata-project/SonataSeoBundle#112]
``` php
/**
* @param mixed $meta
*
* @return array
*/
private function normalize($meta)
{
    if (is_string($meta)) {
       return array($meta, array());
    }

    return $meta;
}
```

According to its PhpDoc, this method should return always an array, but if we pass a parameter that is not a string, it will return that parameter. And this will cause a fatal error inside setMetas() method.

This create inconsistency between addMeta() and setMetas() methods, because if we use a float or an integer as meta content value, addMeta() will accept it but setMetas() won't.

So, depending on what behaviour you expect(and if you consider this a bug) there are different fixes:
- Accept only string as meta value content and add an exception otherwise
- Accept other values, like int and float, inside setMetas() methods

**Comment by OskarStark** [comment]
@slash890 can you provide a PR and a simple testcase?

**Comment by slash890** [comment]
Here the PR
#115
