### ISSUE TITLE
Breadcrumb block attributes

### ISSUE THREAD

**Issue by rYsvelain** [sonata-project/SonataSeoBundle#113]
Hello,

I was doing this part of the documentation : https://sonata-project.org/bundles/seo/master/doc/reference/breadcrumb.html

But the BaseBreadcrumbMenuBlockService class, has the factory and the context attributes which are private. The documentation ask to extend this class, but If I want to use the factory in order to create a separate menu I can't.

It would be better to have these attributes in protected ?

**Comment by Th3Mouk** [comment]
Hello ! Why U don't use the factory and context getter meantime ?

Can you provide a PR with the correction ? Thx
