### ISSUE TITLE
htmlentities seems break special chars in meta properties

### ISSUE THREAD

**Issue by Pop-Code** [sonata-project/SonataSeoBundle#13]
The sonata seo twig extension use in the normalize method the function htmlentities.

In my object i have string in french, using chars like é à and others.
Those chars are translated to &eacute utf8 strings.

Those strings are not parsed by facebook. 
How should i do to get pretty formated string ?

If i remove the htmlentities method this is working.

**Comment by Bencsi** [comment]
+1

**Comment by bertrandg** [comment]
+1

**Comment by lvillanne** [comment]
+1

**Comment by greg0ire** [comment]
`htmlspecialchars` might be better for that job.

**Comment by kunicmarko20** [comment]
@greg0ire are you sure? It seems `+1` is also working for people.

**Comment by kunicmarko20** [comment]
+1

**Comment by bornemisza** [comment]
+1

**Comment by core23** [comment]
-12514565156
