### ISSUE TITLE
symfony 3.2 support

### ISSUE THREAD

**Issue by anboo** [sonata-project/SonataSeoBundle#192]
$ composer require sonata-project/seo-bundle
Using version ^2.1 for sonata-project/seo-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/assetic-bundle v2.8.1
    - Conclusion: don't install symfony/assetic-bundle v2.8.1
    - twig/twig v1.12.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.12.3 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.1 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.13.2 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.14.0 conflicts with symfony/assetic-bundle[v2.8.1].
    - twig/twig v1.14.1 conflicts with symfony/assetic-bundle[v2.8.1].

**Comment by anboo** [comment]
Please, update twig/twig to 1.27 version. I see it solve problem with assetic bundle in symfony 3.

**Comment by jordisala1991** [comment]
There is no code blocking twig 1.27, so this is not an issue on our side, Closing. Ping me if this is still relevant
