### ISSUE TITLE
Request for a new tagged release

### ISSUE THREAD

**Issue by votemike** [sonata-project/SonataSeoBundle#207]
#197 allowed this bundle to be used with Twig 2.0, however there doesn't appear to be a tagged release with this update in it.  
This presents a problem when trying to use symfony-cmf/seo-bundle and Twig 2.x together as symfony-cmf/seo-bundle requires `sonata-project/seo-bundle: ^1.1.3|^2.0` which does not resolved to an installable set of packages.

(I apologise if a GH issue is not the correct way to request a new tagged version)

**Comment by greg0ire** [comment]
It is a correct way. Another way is to use the sf slack, channel `#sonata`. I'm forwarding your request.

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataSeoBundle/releases/tag/2.2.0
