### ISSUE TITLE
TwitterEmbedTweetBlock doesn't work with latest versions of Guzzle

### ISSUE THREAD

**Issue by Xymanek** [sonata-project/SonataSeoBundle#270]
The reason is that guzzle has changed their namespaces. Here is the block's code:

https://github.com/sonata-project/SonataSeoBundle/blob/1cc2c6bffb755dd2bc6eccc975ecb1fdb44af1d9/src/Block/Social/TwitterEmbedTweetBlockService.php#L56

And here is the source code for guzzle's client: https://github.com/guzzle/guzzle/blob/c9615e7a872f18f63970b558f2555697f03e7803/src/Client.php#L2-L25

**Comment by kunicmarko20** [comment]
We support:
 https://github.com/sonata-project/SonataSeoBundle/blob/1cc2c6bffb755dd2bc6eccc975ecb1fdb44af1d9/composer.json#L38

We should change that to 6.* and fix that namespace or add an if that would allow both namespaces

**Comment by jordisala1991** [comment]
It would be better to just do a curl, we are using a big library for this little usage.

**Comment by Xymanek** [comment]
> just do a curl

Guzzle gives benefit of injecting it and thus can be replaced/etc for testing/etc

> big library for this little usage

Yeah, might make sense to use a more lightweight library than guzzle

**Comment by kunicmarko20** [comment]
Shouldn't http-plug allow us to use buzz/guzzle and in our case, for testing, it can be buzz?

**Comment by core23** [comment]
This #161 could fix the problem by using httplug
