### ISSUE TITLE
Add the current Symfony locale to the <html> attribute by default

### ISSUE THREAD

**Issue by leroy0211** [sonata-project/SonataSeoBundle#318]
## Feature Request

Symfony has a Translation component which can be used to set the language of the page in the `<html>` attribute.

The `<html>` attribute can be auto appended with the configured language in Symfony like `<html lang="en">` or even more specific `<html lang="en-GB">`.

**Comment by core23** [comment]
Can you provide a PR @leroy0211 ?

**Comment by apuzanoff** [comment]
This issue is still actual.
I have to use `<html lang="{{ app.request.locale }}-{{ country_key }}" {{ sonata_seo_html_attributes() }}>` construction but not SEO Bundle ability
