### ISSUE TITLE
Add configurable prefix and suffix for the <title> 

### ISSUE THREAD

**Issue by leroy0211** [sonata-project/SonataSeoBundle#319]
## Feature Request

It would be great to have a configurable prefix and suffix for the `<title>` element. 

When you use `->setTitle()` or `->addTitle()` the prefix and suffix will be added to the result. The prefix and suffix should be configured in the configuration but may be overwritten by the user when requesting the `sonata.seo.page` service.

**Comment by core23** [comment]
Can you provide a PR @leroy0211 ?

**Comment by core23** [comment]
Duplicate of https://github.com/sonata-project/SonataSeoBundle/issues/157
