### ISSUE TITLE
Make an alias Service So the SeoPageInterface can be autowired

### ISSUE THREAD

**Issue by leroy0211** [sonata-project/SonataSeoBundle#320]
## Feature Request

Right now whenever you want to alter the Seo attributes, you need to do the following:

```
$seoPage = $this->get('sonata.seo.page')
```

This is only possible when you have the `Container` available. That's not always the case. 
Since Symfony uses `autowiring` and `autoconfiguring` it would be great to just use `DependencyInjection`. This means that developers just use the `SeoPageInterface` whenever they want. 

I am aware you can configure every service to use the `@sonata.seo.page` service, but that will end up in a lot of configuration while it can be reduced to a Service alias.

**Comment by OskarStark** [comment]
Great idea 👍 

Would you mind create a PR like this one: https://github.com/sonata-project/SonataMediaBundle/pull/1522 ?

**Comment by leroy0211** [comment]
@OskarStark done. 
Just a minor question, do you stil accept PR's for the 1.x branch? Because we have a project not yet on PHP7.x which is in desperate need of these changes too.
