### ISSUE TITLE
User Deprecated: The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead

### ISSUE THREAD

**Issue by kuraobi** [sonata-project/SonataSeoBundle#339]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/exporter   2.0.1 2.0.1 Lightweight Exporter library
sonata-project/seo-bundle 2.7.0 2.7.0 Symfony SonataSeoBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/framework-bundle           v4.3.0  v4.3.1  Symfony FrameworkBundle
symfony/twig-bridge                v4.3.0  v4.3.1  Symfony Twig Bridge
symfony/twig-bundle                v4.3.0  v4.3.1  Symfony TwigBundle
...
```

#### Twig

```
twig/twig       v2.11.0 v2.11.2 Twig, the flexible, fast, and secure template language for PHP
```

#### PHP version

```
$ php -v
PHP 7.3.4 (cli) (built: Apr  6 2019 02:50:26) ( NTS )
```

## Subject

The current SonataSeoBundle release requires :
```
"twig/twig": "^1.35 || ^2.4"
```
The spaceless tag is now deprecated since twig 2.7 and should be replaced with the spaceless filter, but the spaceless filter was introduced in twig 1.38. Should we drop support for 1.35 - 37 or just not use spaceless tags?

## Steps to reproduce

Render any Sonata SEO tag in your page

## Expected results

No deprecation warning

## Actual results

```
User Deprecated: The spaceless tag is deprecated since Twig 2.7, use the spaceless filter instead
```

**Comment by greg0ire** [comment]
Hey! Nice to see you there :) You might be interested in reading https://github.com/sonata-project/SonataAdminBundle/pull/5576
