### ISSUE TITLE
multilanguage support?

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataSeoBundle#43]
in https://github.com/ElectricMaxxx/CmfSeoBundle/issues/26 we are wondering how the sonata seo bundle does multilanguage on things like the default site title, description or the keywords.

/cc @ElectricMaxxx

**Comment by Sshuichi** [comment]
Any news about this ?

**Comment by ElectricMaxxx** [comment]
Using the CMF and PHPCR the CmfSeoBundle would do that for you.

Am 23.11.2015 um 22:26 schrieb Aymane:

**Comment by apuzanoff** [comment]
I still do not understand if there is support for multilanguage in sonata-project/SonataSeoBundle
Or olny way to have multilanguage support is using symfony-cmf/seo-bundle which is unsupported for years ?
