### ISSUE TITLE
BaseBreadcrumbMenuBlockService is broken in master

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataSeoBundle#446]
In https://github.com/sonata-project/SonataSeoBundle/pull/399 (a PR made against master), `BaseBreadcrumbMenuBlockService` parent was changed from `Sonata\BlockBundle\Block\Service\MenuBlockService` to `Sonata\BlockBundle\Block\Service\AbstractBlockService`. This results in lost functionality as revealed by a test I wrote in https://github.com/sonata-project/SonataSeoBundle/pull/426

More details at https://github.com/sonata-project/SonataSeoBundle/commit/84355f6ed55d7a3c95dcfdf2bbfbc1f6ee385eee#r42221263

Might be related to #443 too.

**Comment by core23** [comment]
Closing this in favor of #520
