### ISSUE TITLE
[RFC] Remove twitter / facebook / pinterest blocks

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataSeoBundle#519]
To reduce the complexity and sharpen the focus of this bundle, we should split(?) this bundle:

**BlockBundle**
- Reusable block component

**SeoBundle**
- SEO related components (meta information, breadcrumb)

**SocialBundle**
- Social components (blocks)

**Comment by core23** [comment]
This could solve this https://github.com/sonata-project/SonataSeoBundle/pull/516

**Comment by wbloszyk** [comment]
Great idea.

IMHO we should move SocialBlocks directly to BlockBundle(3.x and 4.x with conflict to previus version), becouse we have other blocks there which are not depends on other bundle (like MenuBlockService) . Then we can remove BlockBundle dependency and add it to sugestion in SeoBundle. So it will depends on user which version of BlockBundle want to use.

**Comment by OskarStark** [comment]
Or me can create a social block bundle?

**Comment by wbloszyk** [comment]
> Or we can create a social block bundle?

It depends what we want:
- move it to BlockBundle - if we want only keep social blocks
- seperate bundle - for blocks and extra features (like twitter API, extracted from `TwitterEmbedTweetBlockService`)

**Comment by core23** [comment]
> Create bundle only for few blocks have no sense, but for other feature I vote for yes.

It depends 😆 Some social blocks require other components (e.g. http client) which are only needed for a bunch of classes. Most classes don't need this client.

We could solve this by making the http client an optional dependency. I'm not a big fan of optional dependencies (anymore), because they can cause troubles when composer tries to determine the needed dependencies. We need to add `require-dev` and `conflict` dependencies to make sure that the optional dependency will always work.

Smaller projects require more maintenance work (in theory) but should require less work when releasing new major versions.

**Comment by OskarStark** [comment]
I would love to go to monorepo 🤣😳

**Comment by core23** [comment]
> I would love to go to monorepo 🤣😳

Can you do this? 😄

**Comment by OskarStark** [comment]
Not so much time right now and no experience... 😬
