### ISSUE TITLE
[RFC] Rethink breadcrumbs

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataSeoBundle#520]
## Feature Request

There are some issues with the breadcrumb component (#446, #443). They are caused by a design issue that was introduced a long time ago.

At the moment a breadcrumb MUST extend the `BaseBreadcrumbMenuBlockService` which is a **breadcrumb** AND a **block**. This component is then render via https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/MenuBlockService.php. So a block renders an other block oO

A better idea is to split this component into a breadcrumb and a block which renders a breadcrumb.

```php
namespace Sonata\SeoBundle\Breadcrumb;

interface Breadcrumb 
{
    public function configureSettings(OptionsResolver $resolver): void;

    public function getMenu(array $options = []): ItemInterface;
}
```

**Comment by wbloszyk** [comment]
If I undersand correctly for now it is working as block: 
https://github.com/sonata-project/ecommerce/blob/3.x/src/ProductBundle/Block/CatalogBreadcrumbBlockService.php
Render breadcrumb it possible by something like:
`{{ sonata_block_render('sonata.product.block.breadcrumb') }}`
or
`{{ sonata_block_render_event('breadcrumb', { 'context': 'news_post', 'post': post, 'current_uri': app.request.requestUri }) }}`

IMO we should change for example `CatalogBreadcrumbBlockService` to `CatalogBreadcrumbService` and render it by twig function. Additionaly for use it by block we can add final `BreadcrumbBlockService` which will render `CatalogBreadcrumbService` object.

Also we should allow use advance build menu and display only this `ItemInterface` where `isCurrent()` return `true`. IMO this case can be render by `MenuBlockService` with setting - `display_currents_only` = true.
