### ISSUE TITLE
knp/menu-bundle should probably be part of the dependencies

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataSeoBundle#56]
After installing the bundle, I get this error message : 

> The service "sonata.seo.block.breadcrumb.homepage" has a dependency on a non-existent service "knp_menu.menu_provider".

I think the bundle should require `knp/menu-bundle` or at least `knp/menu`, shouldn't it ?

**Comment by rande** [comment]
The KnpMenuBundle is optional. You need it only if you use the BlockBundle with PageBundle.
