### ISSUE TITLE
Autogenerate meta property og:url

### ISSUE THREAD

**Issue by apuzanoff** [sonata-project/SonataSeoBundle#593]
## Feature Request
It would be great if SonataSeoBundle could automatically generate a value for meta property 'og:url'. Unfortunately, I did not find in the documentation a way to describe this property using a config. Apparently the only way is dynamic initialization by addMeta() method.

**Comment by core23** [comment]
Can you provide a PR that provides this feature @apuzanoff ?

**Comment by apuzanoff** [comment]
what do you mean under PR ? Sorry I am not familiar with this abbreviation

**Comment by VincentLanglet** [comment]
Pull Request

**Comment by core23** [comment]
After thinking a little bit more about this feature, I'm not sure if this is good idea. 

According to https://ogp.me/, it should be a canonical url which can cause problems if you have multiple routes for the same action (e.g. short link and normal url).
