### ISSUE TITLE
Fatal error in Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php line 120

### ISSUE THREAD

**Issue by alicomo** [sonata-project/SonataSeoBundle#66]
After updating yesterday to dev-master I got this issue

FatalErrorException: Error: Call to undefined method Knp\Menu\MenuItem::setCurrentUri() in /Users/shaduli/projects/tpse/vendor/sonata-project/seo-bundle/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php line 120
in /Users/shaduli/projects/tpse/vendor/sonata-project/seo-bundle/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php line 120

I found setCurrentUri has been removed from Knp\Menu\MenuItem and renamed to setCurrent()

**Comment by rande** [comment]
fixed in 854b988a19eed3962e0e6f152feea3e195b36aa3
