### ISSUE TITLE
BaseBreadcrumbMenuBlockService changed from 2.x to 3.x

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataSeoBundle#685]
#### Sonata packages

Latest version 4, checking on SonataPageBundle

#### Symfony packages

Latest 6.1.x release

#### PHP version

All php versions supported (from 7.4 to 8.1)

## Subject

Not sure how to fix it, or what is the best solution, but from 2.x to 3.x we removed EditableBlockInterface from BaseBreadcrumbMenuBlockService.

We stop extending this other class from SonataBlockBundle, but not sure why: https://github.com/sonata-project/SonataBlockBundle/blob/4.x/src/Block/Service/MenuBlockService.php

Maybe it was to make that class final, but with that move we broke that block.

Possible solutions:
1. Revert to extend MenuBlockService
2. Implement EditableBlockService directly on BaseBreadcrumbMenuBlockService
3. ... others?

## Minimal repository with the bug

https://github.com/sonata-project/SonataPageBundle/pull/1552

## Steps to reproduce

Try to use https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Block/BreadcrumbBlockService.php block.

## Expected results

Be able to use that SonataPageBundle block

## Actual results

It will break because this class does not implements EditableBlockInterface

**Comment by VincentLanglet** [comment]
Can't we extends BaseBreadcrumbMenuBlockService is PageBundle and implements EditableBlockService in PageBundle ?

**Comment by jordisala1991** [comment]
Is that a better option than what was prior to the pr that broke the integration? Previously the block had those fields because it extended a class from block bundle that had it. Shouldnt the block provide everything needed to use it?

**Comment by VincentLanglet** [comment]
> Is that a better option than what was prior to the pr that broke the integration? Previously the block had those fields because it extended a class from block bundle that had it. Shouldnt the block provide everything needed to use it?

I wasn't sure the EditableBlock feature was needed for everyone extending this block or it was possible to create blocks extending this one which doesn't need the EditableBlock.

But yes, I'm not against implementing Editable block interface here. And it would be BC
