### ISSUE TITLE
addTitle 

### ISSUE THREAD

**Issue by zorg-iris** [sonata-project/SonataSeoBundle#81]
hi, i m using sonata seo lake this : 
```php
		// Seo page
		$seoPage = $this->container->get ( 'sonata.seo.page' );
		$seoPage->addMeta ( 'name' , 'identifier-url' , $domaine . $identifierUrl )
				->addTitle ( $title );
```
but whem i ```addTitle``` it concatenates and me some time i need concatenates and same time not.
how i can do this ?
thank.

**Comment by cmizzi** [comment]
If you want concatenates title, you have to use `addTitle()` method. Otherwise, use `setTitle()` method.

[Source code](https://github.com/sonata-project/SonataSeoBundle/blob/master/Seo/SeoPage.php#L80-L98)

**Comment by OskarStark** [comment]
@zorg-iris can we close this issue?

**Comment by core23** [comment]
This issue should be fixed. Please have a look at the docs.

If this is still present, feel free to reopen this issue
