### ISSUE TITLE
Prevent using plain mysql in sitemap-config

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataSeoBundle#83]
As you can see [in the documentation](http://sonata-project.org/bundles/seo/master/doc/reference/sitemap.html) you have to use plain mysql in configuration files to make the sitemap generator work. It would be great to have a nice interface at this place to control whats visible in the sitemap.

**Comment by rande** [comment]
The sitemap generator also accept service. I just update the documentation: https://github.com/sonata-project/SonataSeoBundle/commit/ee2f6aaae456cb1aa09815cdc4efb1bdd8dbcf15

**Comment by blaues0cke** [comment]
Nice! Thank you.
