### ISSUE TITLE
problems while updating sonata e-commerce

### ISSUE THREAD

**Issue by filipjakubowski** [sonata-project/SonataSeoBundle#85]
Problem 1
    - Installation request for sonata-project/ecommerce dev-develop -> satisfiable by sonata-project/ecommerce[dev-develop].
    - sonata-project/ecommerce dev-develop requires sonata-project/seo-bundle ~2.0@dev -> no matching package found

**Comment by rande** [comment]
This is a work in progress. Please review: https://gist.github.com/rande/9c0cfbd751d3e64b893f
