### ISSUE TITLE
Unrecognized option "default" under "sonata_seo"

### ISSUE THREAD

**Issue by rasanga** [sonata-project/SonataSeoBundle#86]
After upgrading "sonata-project/seo-bundle" to version 1.1.10 from 1.1.8  I am getting following error message:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "default" under "sonata_seo"                               
                                                     
I checked the CHANGEDLOG but I could not find anything regards but seems to be the configuration has been changed, my sonata_seo configuration looking like following:

# app/config/config.yml
sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            Sonata Project
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow

**Comment by nlzet** [comment]
I had the same problem, I think I copied my setup from the sandbox. From what i've found quickly the option "default" belongs to your "page" option and not as a main option.

So replace:

    sonata_seo:
        default: sonata.seo.page.default
        encoding: UTF-8
        page:
            title: Sonata Project
            ...

With:

    sonata_seo:
        encoding: UTF-8
        page:
            default: sonata.seo.page.default
            title: Sonata Project
            ...

**Comment by OskarStark** [comment]
:+1: thx @mvhirsch

**Comment by nicolasricci** [comment]
documentation update in progress #90

**Comment by OskarStark** [comment]
ping @rande why is the documentation still the old one on the website?

can you please update this?
https://sonata-project.org/bundles/seo/master/doc/reference/installation.html

**Comment by rande** [comment]
@OskarStark the documentation is now uptodate

**Comment by OskarStark** [comment]
thank you!

2015-09-02 18:38 GMT+02:00 Thomas <notifications@github.com>:

**Comment by didando8a** [comment]
Perfect!!! Thanks
