### ISSUE TITLE
Sonata SEO Bundle Site MAP

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataSeoBundle#88]
I am using sonata seo bundle and knp paginator bundle. My Question is When I added new custom static url like :-(www.symfony.in/blog) in our KNP Menu.It's added successfully and it's show on hole website in menu But When I run the :-

php app/console sonata:seo:sitemap --scheme=http web www.symfony.in --env=prod
Command execute successfully But in sitemap Blog url(www.symfony.in/blog) not added.

Any one know how to add custom url in Sonata SEO Bundle in Sitemap ?

I am google it but nothing found !

Same question ask here :- stackoverflow.com/questions/29406747/sonata-seo-bundle-site-map

Thnaks!

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
