### ISSUE TITLE
using seo with sonata admin 2.3.3 

### ISSUE THREAD

**Issue by jmeyo** [sonata-project/SonataSeoBundle#95]
Somehow can't use seo bundle within my backend configuration

latest stable version is sonata-project/seo-bundle 2.0.0

latest stable sonata admin is sonata-project/admin-bundle (2.3.3) implies sonata-project/block-bundle (2.2.13)

and then I run into compatibility issues (linked to refactoring of ErrorElement in march), which have been fixed in sonata-project/block-bundle (2.3.0)

```
PHP Fatal error:  Declaration of Sonata\SeoBundle\Block\Social\EmailShareButtonBlockService::validateBlock() must be compatible 
with Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in [...]
```
Thanks for your time

**Comment by Soullivaneuh** [comment]
Hi @jmeyo. Which version of sonata are you using? Could you please update and tell me if you still have this issue?

**Comment by jmeyo** [comment]
It's a one year old issue, I found a workaround I guess, and I don't event know on which project I had the problem, so just close it.
